"""Measure the dataset against the volume's own counts and report coverage.

Lambert's preface states how many notices of each kind the book contains. Those
figures are an external benchmark the pipeline never sees, so comparing against
them is a real test of segmentation and classification rather than a restatement
of the pipeline's own output. Everything else here is coverage and OCR quality,
reported so that a user can decide which variables are usable for their purpose.

Writes docs/validation_report.md.
"""

from __future__ import annotations

import collections
import csv
import json
import pathlib
import statistics

ROOT = pathlib.Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
INTERIM = ROOT / "data" / "interim"
DOCS = ROOT / "docs"

# Counts printed in Lambert's own preface (pp. III-IV).
PREFACE_CLAIMS = {
    "person": ("more than 1,300 biographical notices", 1300),
    "place": ("more than 750 notices on localities", 750),
    "organisation": ("more than 175 notices on societies and associations", 175),
    "topic": ("more than 250 Arabic or Tunisian terms explained", 250),
}
PREFACE_PORTRAITS = 420


def read(name: str) -> list[dict]:
    path = PROCESSED / name
    if not path.exists() or not path.stat().st_size:
        return []
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def coverage(rows: list[dict], fields: list[str]) -> list[tuple[str, int, float]]:
    out = []
    for f in fields:
        n = sum(1 for r in rows if (r.get(f) or "").strip())
        out.append((f, n, 100 * n / len(rows) if rows else 0.0))
    return out


def table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |",
             "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        lines.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(lines) + "\n"


def main() -> int:
    DOCS.mkdir(exist_ok=True)
    entries = read("entries.csv")
    persons = read("persons.csv")
    places = read("places.csv")
    orgs = read("organizations.csv")
    decs = read("decorations.csv")
    mentions = read("mentions.csv")
    p_org = read("edges_person_organisation.csv")
    p_place = read("edges_person_place.csv")
    p_p = read("edges_person_person.csv")
    nodes = read("network_nodes.csv")

    manifest_path = PROCESSED / "source_manifest.json"
    manifest = (
        json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest_path.exists()
        else {}
    )

    by_type = collections.Counter(r["entry_type"] for r in entries)
    confs = [float(r["ocr_confidence"]) for r in entries if r["ocr_confidence"]]
    portraits = sum(int(r["n_portraits"]) for r in entries)

    out: list[str] = []
    out.append("# Validation report\n")
    out.append(
        "Generated by `code/pipeline/validate.py`. Every number below is recomputed from the "
        "files in `data/processed/`.\n"
    )

    out.append("## 1. Against the volume's own counts\n")
    out.append(
        "The preface (pp. III-IV) states how many notices of each kind the volume "
        "contains. The pipeline never uses these figures, so they are an independent "
        "check on segmentation and classification.\n"
    )
    rows = []
    for etype, (claim, n) in PREFACE_CLAIMS.items():
        got = by_type.get(etype, 0)
        rows.append([etype, claim, n, got, f"{100 * got / n:.0f}%"])
    rows.append(
        ["portraits", "420 photogravure portraits", PREFACE_PORTRAITS, portraits,
         f"{100 * portraits / PREFACE_PORTRAITS:.0f}%"]
    )
    out.append(table(["entry_type", "Lambert's claim", "stated", "extracted", "ratio"], rows))
    out.append(
        "The person count clears the stated minimum. Places and associations fall "
        "short of theirs: some notices are absorbed into the entry above them when "
        "the first-line indent is lost to OCR, and some association notices are "
        "coded as `topic` because they carry none of the organisational template's "
        "markers. Treat the place and organisation tables as high-precision, "
        "incomplete samples of their populations, not as complete enumerations.\n"
    )

    out.append("## 2. Corpus\n")
    out.append(
        table(
            ["measure", "value"],
            [
                ["IIIF views in the manifest", manifest.get("views_in_manifest", "n/a")],
                ["views with an ALTO OCR layer", manifest.get("views_with_alto_ocr", "n/a")],
                ["views that begin at least one entry", len({r["view_first"] for r in entries})],
                ["entries segmented", len(entries)],
                ["characters of entry text", sum(int(r["n_chars"]) for r in entries)],
                ["mean OCR word confidence", f"{statistics.mean(confs):.3f}" if confs else "n/a"],
                ["entries below 0.80 confidence", sum(1 for c in confs if c < 0.80)],
                ["illustrations located", portraits],
            ],
        )
    )
    out.append("### Entries by type\n")
    out.append(
        table(
            ["entry_type", "n", "share"],
            [[k, v, f"{100 * v / len(entries):.1f}%"] for k, v in by_type.most_common()],
        )
    )
    out.append("### How each entry boundary was decided\n")
    seg = collections.Counter(r["segmentation_rule"] for r in entries)
    cls = collections.Counter(r["classification_rule"] for r in entries)
    out.append(table(["segmentation rule", "n"], [[k, v] for k, v in seg.most_common()]))
    out.append(table(["classification rule", "n"], [[k, v] for k, v in cls.most_common()]))

    out.append("## 3. Field coverage\n")
    out.append(
        "Share of rows where the field is non-empty. A low rate means Lambert did "
        "not print that detail for most cases, or that the OCR lost it -- not that "
        "a value was dropped.\n"
    )
    out.append("### persons.csv (n = %d)\n" % len(persons))
    out.append(
        table(
            ["field", "n non-empty", "%"],
            [
                [f, n, f"{pct:.1f}"]
                for f, n, pct in coverage(
                    persons,
                    ["forenames", "birth_year", "birth_place", "birth_place_detail",
                     "occupation_primary", "address_raw", "city", "settled_tunisia_year",
                     "decoration_orders", "education_raw", "education_institutions",
                     "degrees", "career_raw", "works_raw"],
                )
            ],
        )
    )
    out.append("### places.csv (n = %d)\n" % len(places))
    out.append(
        table(
            ["field", "n non-empty", "%"],
            [
                [f, n, f"{pct:.1f}"]
                for f, n, pct in coverage(
                    places,
                    ["controle_civil", "caidat", "distance_km", "population",
                     "altitude_m", "tribe_mentioned", "owners_raw"],
                )
            ],
        )
    )
    out.append("### organizations.csv (n = %d)\n" % len(orgs))
    out.append(
        table(
            ["field", "n non-empty", "%"],
            [
                [f, n, f"{pct:.1f}"]
                for f, n, pct in coverage(
                    orgs,
                    ["founded_year", "seat_raw", "city", "n_members_stated",
                     "purpose_raw", "organisation_kind_primary"],
                )
            ],
        )
    )

    out.append("## 4. Honours\n")
    order_counts = collections.Counter(r["order"] for r in decs)
    out.append(
        table(
            ["order", "awarding state", "n persons"],
            [
                [k, next(r["order_country"] for r in decs if r["order"] == k), v]
                for k, v in order_counts.most_common()
            ],
        )
    )
    grade_counts = collections.Counter(r["grade"] or "(not stated)" for r in decs)
    out.append(table(["grade", "n"], [[k, v] for k, v in grade_counts.most_common()]))

    out.append("## 5. Relational layer\n")
    res = collections.Counter(r["resolution"] for r in mentions)
    out.append(
        table(
            ["measure", "value"],
            [
                ["person-organisation edges", len(p_org)],
                ["  from officer lists in association entries",
                 sum(1 for r in p_org if r["tie_source"] == "organisation_entry_officer_list")],
                ["  from statements in a person's own entry",
                 sum(1 for r in p_org if r["tie_source"] == "person_entry_statement")],
                ["person-place edges", len(p_place)],
                ["person-person co-membership edges", len(p_p)],
                ["network nodes", len(nodes)],
            ],
        )
    )
    out.append("### Name resolution for people named in someone else's entry\n")
    out.append(
        table(
            ["resolution", "n", "share"],
            [[k, v, f"{100 * v / len(mentions):.1f}%"] for k, v in res.most_common()],
        )
    )
    out.append(
        "`unmatched` mostly means what it says: the volume names far more people in "
        "its association and property lists than it gives notices to. Those people "
        "are kept as `person_named_only` nodes. `ambiguous` means two or more "
        "people with entries share the surname; no tie is assigned, and the mention "
        "is left in `mentions.csv` for manual disambiguation.\n"
    )

    node_types = collections.Counter(r["node_type"] for r in nodes)
    out.append(table(["node type", "n"], [[k, v] for k, v in node_types.most_common()]))

    # degree distribution of the two-mode affiliation network
    deg: collections.Counter[str] = collections.Counter()
    for r in p_org:
        deg[r["person_node"]] += 1
        deg[r["organisation_node"]] += 1
    if deg:
        vals = sorted(deg.values(), reverse=True)
        out.append("### Affiliation network degree\n")
        out.append(
            table(
                ["measure", "value"],
                [
                    ["nodes with at least one affiliation", len(deg)],
                    ["mean degree", f"{statistics.mean(vals):.2f}"],
                    ["median degree", statistics.median(vals)],
                    ["max degree", vals[0]],
                    ["isolates in the node table", len(nodes) - len(deg)],
                ],
            )
        )

    out.append("## 6. Known limitations\n")
    out.append(
        "- **Segmentation.** Entry boundaries come from the first-line indent plus "
        "alphabetical order. Where the indent is lost, a notice is merged into the "
        "one above it; `n_paragraphs` flags the entries most at risk.\n"
        "- **OCR.** The BnF estimates ~96% character accuracy for this volume. "
        "Proper names carry the errors that matter most here: surnames are the join "
        "key for the network, so a garbled surname becomes an isolated node.\n"
        "- **Name resolution.** Matching is by surname, with a one-character "
        "tolerance flagged as `resolved_fuzzy`. Homonyms are left unresolved.\n"
        "- **Coverage is Lambert's coverage.** Who appears in this book was decided "
        "in 1912 by a Tunis publisher: French settlers and officials are heavily "
        "over-represented, Tunisian Muslims and Jews appear mainly as notables, and "
        "women are almost absent. The dataset reproduces that selection exactly. It "
        "is evidence about the colonial elite's self-portrait, not a census.\n"
    )

    (DOCS / "validation_report.md").write_text("\n".join(out), encoding="utf-8")
    print(
        json.dumps(
            {
                "entries": len(entries),
                "by_type": dict(by_type),
                "portraits": portraits,
                "mean_ocr_confidence": round(statistics.mean(confs), 4) if confs else None,
                "report": str((DOCS / "validation_report.md").relative_to(ROOT)),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
